[package]
name = "tree-sitter-slang"
description = "slang grammar for the tree-sitter parsing library"
version = "0.2.2"
keywords = ["incremental", "parsing", "slang"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/theHamsta/tree-sitter-slang"
edition = "2021"
license = "MIT"
authors = ["Stephan Seitz"]

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.10"

[build-dependencies]
cc = "1.0.73"
